image: node:22 

pipelines:
  default:
    - step:
        name: Install Dependencies, Install Playwright, and Run API Tests
        caches:
          - node 
        script:
          - echo 
          - npm ci 
          - echo 
          - npm install -g playwright
          - playwright install --with-deps
          - echo 
          - npx playwright test --reporter=html

        artifacts:
          - playwright-report/**
          - test-results/**
